name: Update Website
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/biomappings/resources/*.sssom.tsv"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: |
          pip install tox tox-uv
      - name: Create local changes
        run: tox -e update
        env:
          NDEX_USERNAME: ${{ secrets.NDEX_USERNAME }}
          NDEX_PASSWORD: ${{ secrets.NDEX_PASSWORD }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "🗺️ Update summaries" -a
      - name: Push changes
        uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
